CREATE TABLE Users(
      UserID NUMBER,
      FName VARCHAR(100) NOT NULL,
      LName VARCHAR(100) NOT NULL,
      Password VARCHAR(100) NOT NULL,
      Email VARCHAR(200) NOT NULL,
      Address VARCHAR(200) NOT NULL,
      Tel NUMBER,
      UserType VARCHAR(50) NOT NULL,
      CreatedAt TIMESTAMP,
      UpdatedAt TIMESTAMP
);

ALTER TABLE Users ADD (
    CONSTRAINT userID_pk PRIMARY KEY (UserID));
    
CREATE SEQUENCE userID_seq START WITH 1;

CREATE OR REPLACE TRIGGER create_timestamp
BEFORE INSERT ON Users
FOR EACH ROW
BEGIN
    :NEW.CreatedAt := SYSDATE;
    SELECT userID_seq.nextval
    INTO :NEW.UserID
    FROM DUAL;
END;

CREATE OR REPLACE TRIGGER update_timestamp
BEFORE UPDATE ON Users
FOR EACH ROW
BEGIN
    :NEW.UpdatedAt := SYSDATE;
END;